[pyprland]
plugins = [
 "scratchpads",
 "fetch_client_menu"
]
[pyprland.fetch_client_menu]
command = "fetch_client_menu"

[pyprland.variables]
term_classed = "kitty --class"

[scratchpads.term]
animation = "fromTop"
command = "[term_classed] main-dropterm"
class = "main-dropterm"
size = "65% 55%"
max_size = "1920px 100%"
preserve_aspect = true
unfocus = "hide"
lazy = true

[scratchpads.editor]
animation = "fromTop"
command = "[term_classed] helix --title helix -e helix"
class = "helix"
size = "45% 50%"
preserve_aspect = true
max_size = "1920px 100%"
unfocus = "hide"
lazy = true

[scratchpads.clock]
animation = ""
command = "[term_classed] peaclock -e peaclock"
class = "peaclock" #alacritty dosent like tty-clock sometimes. 
lazy = true
size = "50% 45%"
unfocus = "hide"

[scratchpads.btop]
animation = ""
command = "[term_classed] btop --title btop -e btop"
class = "btop"
lazy = true
size = "60% 60%"
unfocus = "hide"

# [scratchpads.volume]
# animation = "fromBottom"
# command = "pavucontrol"
# class = "org.pulseaudio.pavucontrol"
# lazy = true
# size = "40% 60%"
# unfocus = "hide"

# [scratchpads.bluetuith]
# animation = "fromBottom"
# command = "[term_classed] bluetuith --title bluetuith -e bluetuith"
# class = "bluetuith"
# lazy = true
# size = "40% 50%"
# unfocus = "hide"

# [scratchpads.iwgtk]
# animation = "fromBottom"
# command = "iwgtk"
# class = "org.twosheds.iwgtk"
# lazy = true
# size = "40% 50%"
# unfocus = ""

